Improve the `ruleset_rule` `time_frame` documentation
PagerDuty/terraform-provider-pagerduty pull request #340
Opened 2021-05-26 19:29 UTC by metavida

Specifically, the previous description of how to choose a `start_time` value was misleading & did not explain how picking a correct value also involves the specified `timezone`

Also update the code example to demonstrate how to use [the `time_static` resource](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/static) for slightly more human-readable configuration.

2021-05-26 22:31 UTC, stmcallister requested changes
Overall, looks great! Please just update the variables to use the current syntax. Thanks!

2021-05-26 22:31 UTC, stmcallister commented on website/docs/r/ruleset_rule.html.markdown
> +      start_time = "${time_static.eastern_time_at_0930.unix * 1000}"
We're trying to standardize on the syntax introduced in Terraform v0.12 (i think). Please change this to match that notation as well. Essentially, just removing the double-quotes, dollar sign and curly-brackets. :) Something like this

`start_time = time_static.eastern_time_at_0930.unix * 1000`

2021-05-26 22:31 UTC, stmcallister commented on website/docs/r/ruleset_rule.html.markdown
> +      duration = "${2 * 60 * 60 * 1000}"
Similar as the above comment. Please use the v0.12+ syntax for variables.

2021-05-26 22:31 UTC, stmcallister commented on website/docs/r/ruleset_rule.html.markdown
> +  * `duration` - Length of time the schedule will be active in milliseconds. For example `duration = "${2 * 60 * 60 * 1000}"` if you want your rule to apply for 2 hours, from the specified `start_tim
Also here, on the comments from above re: v0.12+ syntax.

2021-05-27 16:38 UTC, metavida commented
Ah! Good catch, @stmcallister ! I've removed those 3 cases of "interpolation-only expressions" in e3f0ec6f1dc89847061d18c7e874e77b90cd7dc3 and tested locally to confirm that the syntax still works as expected 👍

2021-05-27 18:23 UTC, stmcallister approved these changes
👍 🎉  Awesome! Thank you! LGTM.

2021-05-27 18:23 UTC, merged

2021-05-27 19:18 UTC, metavida commented
Thanks so much for getting this merged! Will the documentation changes to live at https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/ruleset_rule when we (i.e. you) release a new version of the terraform provider?