Add ServiceNow extension resource
PagerDuty/terraform-provider-pagerduty pull request #348
Opened 2021-06-23 06:24 UTC by drastawi

Adding a dedicated resource for ServiceNow.

This resource will allow the end-user to avoid perma-diff and mark the password as a sensitive value while providing a simpler dedicated interface (e.g. endpoint URL can be very easily mistaken for the ServiceNow target).

2021-06-29 20:30 UTC, stmcallister requested changes
Thanks for submitting this! I like the direction of this PR. I think it's probably cleaner for extensions like ServiceNow to have their own resource. However, there are several errors in the tests. I've pointed out a few that I see. If you could fix those I'd be happy to merge.

2021-06-29 20:30 UTC, stmcallister commented on pagerduty/resource_pagerduty_extension_servicenow_test.go
> +						"pagerduty_extension_servicenow.foo", "config", "{\"notify_types\":{\"acknowledge\":false,\"assignments\":false,\"resolve\":false},\"restrict\":\"any\"}"),
There is no longer a `config` attribute in this resource. Please break out these checks to match the current schema of the resource.

2021-06-29 20:30 UTC, stmcallister commented on pagerduty/resource_pagerduty_extension_servicenow_test.go
> +						"pagerduty_extension_servicenow.foo", "config", "{\"notify_types\":{\"acknowledge\":true,\"assignments\":true,\"resolve\":true},\"restrict\":\"pd-users\"}"),
Same as above. Please break out these checks to match the current schema

2021-06-29 20:30 UTC, stmcallister commented on pagerduty/resource_pagerduty_extension_servicenow_test.go
> +  extension_schema = data.pagerduty_extension_servicenow_schema.foo.id
I think this was supposed to be referencing `data.pagerduty_extension_schema.foo.id`

2021-06-29 20:30 UTC, stmcallister commented on pagerduty/resource_pagerduty_extension_servicenow_test.go
> +  target = foo.servicenow.com/webhook_foo
I think the `target` value is supposed to be a string.

2021-06-29 20:30 UTC, stmcallister commented on website/docs/r/extension_servicenow.html.markdown
> +  teams = [pagerduty_team.example.id]
The `teams` field is actually deprecated in the `pagerduty_user` resource. For these docs you can just remove the field.

2021-06-29 20:30 UTC, stmcallister commented on website/docs/r/extension_servicenow.html.markdown
> +  escalation_policy       = pagerduty_escalation_policy.example.id
Since we're making other edits to this doc. This should probably match the definition above for `pagerduty_escalation_policy.foo.id`.

2021-07-19 02:58 UTC, drastawi commented
Hey @stmcallister, I ran all the tests now against a live environment. Should all work. Also fixed the corresponding typos on the non-servicenow extension side. Let me know if it looks better now.

2021-07-27 23:26 UTC, stmcallister approved these changes
Thank you! Also, I think `Servicenow` should be `ServiceNow` throughout the code. But, i can make that change before merging. Appreciate the contribution!! 🎉

2021-07-27 23:27 UTC, merged