Add support for Automation Actions' Action association to a Service
PagerDuty/terraform-provider-pagerduty pull request #608
Opened 2023-01-05 21:39 UTC by imjaroiswebdev

Add support for resource `pagerduty_automation_actions_action_service_association`

New tests cases introduced...

```sh
$ make testacc TESTARGS="-run TestAccPagerDutyAutomationActionsActionServiceAssociation"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccPagerDutyAutomationActionsActionServiceAssociation -timeout 120m
?       github.com/terraform-providers/terraform-provider-pagerduty     [no test files]
=== RUN   TestAccPagerDutyAutomationActionsActionServiceAssociation_import
--- PASS: TestAccPagerDutyAutomationActionsActionServiceAssociation_import (15.37s)
=== RUN   TestAccPagerDutyAutomationActionsActionServiceAssociation_Basic
--- PASS: TestAccPagerDutyAutomationActionsActionServiceAssociation_Basic (14.10s)
PASS
ok      github.com/terraform-providers/terraform-provider-pagerduty/pagerduty   30.289s
```

Depends on: https://github.com/heimweh/go-pagerduty/pull/115

2023-01-06 16:08 UTC, mrdubr requested changes
Minor typos and nits

2023-01-06 16:08 UTC, mrdubr commented on website/docs/r/automation_actions_action_service_association.html.markdown
> +  Creates and manages an Automation Actions action assciation with a Service in PagerDuty.
```suggestion
  Creates and manages an Automation Actions action association with a Service in PagerDuty.
```

2023-01-06 16:48 UTC, imjaroiswebdev commented on website/docs/r/automation_actions_action_service_association.html.markdown
> +Actions can be imported using the `id`, e.g.
👍🏽

2023-01-06 16:48 UTC, imjaroiswebdev commented on website/docs/r/automation_actions_action_service_association.html.markdown
> +  Creates and manages an Automation Actions action assciation with a Service in PagerDuty.
👍🏽

2023-01-09 17:00 UTC, mrdubr approved these changes

2023-01-09 17:00 UTC, merged