[ORCA-4601] Add support for Event Orchestration Cache Variables
PagerDuty/terraform-provider-pagerduty pull request #822
Opened 2024-02-16 21:58 UTC by c-kaieong

2024-02-20 21:01 UTC, c-kaieong commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable_test.go
> +			},
The `ForceNew` attribute forces the existing resource to be deleted then completely recreated from scratch. So under the hood, it'd be calling our DELETE API on OrchA, then just POST a new one on OrchB.

I've tested this locally, but doesn't hurt to have another pair of eyes.

2024-02-20 21:01 UTC, c-kaieong commented on pagerduty/event_orchestration_cache_variable_util.go
> +			valid := value >= min && value <= max
Ah, that makes sense! I'll remove it

2024-02-20 21:02 UTC, c-kaieong commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable.go
> +		},
Oh I actually wanted to do this from the very start, but couldn't figure out the syntax to accomplish it. I'll make the quick refactor, thanks!

2024-02-20 21:04 UTC, alenapan commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable_test.go
> +			},
Ah nice! I will test it locally too, but it's good to know that there no "leftover" resources after it was moved to a different parent.

2024-02-20 21:51 UTC, alenapan commented on pagerduty/data_source_pagerduty_event_orchestration_global_cache_variable.go
> +	return dataSourceEventOrchestrationCacheVariableRead(ctx, d, meta, pagerduty.CacheVariableTypeGlobal)
@c-kaieong not sure if the provider or internal docs have the instructions but this command should do it:
```
go mod edit -replace github.com/heimweh/go-pagerduty=github.com/c-kaieong/go-pagerduty@ORCA-4600-introduce-cache-variables && go mod tidy && go mod vendor
```

2024-02-20 22:06 UTC, c-kaieong commented on pagerduty/data_source_pagerduty_event_orchestration_global_cache_variable.go
> +	return dataSourceEventOrchestrationCacheVariableRead(ctx, d, meta, pagerduty.CacheVariableTypeGlobal)
Thanks! The internal docs show how to point to a local directory, but not a branch. I'll add that in

2024-02-20 22:08 UTC, c-kaieong commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable.go
> +		},
I couldn't get the refactor going the way I wanted it. I'm just gonna leave this PR as-is instead of sinking more time into it 😅

2024-02-20 22:08 UTC, c-kaieong commented on pagerduty/event_orchestration_cache_variable_util.go
> +			valid := value >= min && value <= max
Addressed in https://github.com/PagerDuty/terraform-provider-pagerduty/pull/822/commits/844a929d19480d10013dd4be9ca69ed963488d98

2024-02-20 22:09 UTC, c-kaieong commented on pagerduty/event_orchestration_cache_variable_util.go
> +		return []*schema.ResourceData{}, fmt.Errorf("Error importing cache variable. Expected import ID format: <orchestration_id>:<cache_variable_id>")
Addressed in https://github.com/PagerDuty/terraform-provider-pagerduty/pull/822/commits/844a929d19480d10013dd4be9ca69ed963488d98

2024-02-20 22:13 UTC, c-kaieong commented on pagerduty/data_source_pagerduty_event_orchestration_global_cache_variable.go
> +	return dataSourceEventOrchestrationCacheVariableRead(ctx, d, meta, pagerduty.CacheVariableTypeGlobal)
https://github.com/PagerDuty/terraform-provider-pagerduty-internal/pull/8

2024-02-20 22:14 UTC, alenapan commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable_test.go
> +			},
Ok I'm running into some errors when trying to use a local provider so need to troubleshoot. But if you tested it locally and confirmed that a cache variable belonging to the old parent gets deleted I think we're good.

2024-02-20 22:14 UTC, alenapan approved these changes
LGTM 👍

2024-03-26 16:02 UTC, imjaroiswebdev requested changes
@c-kaieong before marking this as approved there are some comments to address please.

2024-03-26 16:02 UTC, imjaroiswebdev commented on go.mod
> +replace github.com/heimweh/go-pagerduty => github.com/c-kaieong/go-pagerduty v0.0.0-20240321202501-cb1dc594997d
**Reminder:** Drop replace and update `heimweh/go-pagerduty` once https://github.com/heimweh/go-pagerduty/pull/149 gets merged.

2024-04-02 23:19 UTC, metavida commented on pagerduty/resource_pagerduty_event_orchestration_global_cache_variable_test.go
> +	orch := fmt.Sprintf("tf_orchestration_%s", acctest.RandString(5))
Confirmed fixed in d4d151e55bca15bb24627860a9aa592d56bea9f7

2024-04-02 23:20 UTC, metavida commented on pagerduty/event_orchestration_cache_variable_util.go
> +			time.Sleep(30 * time.Second)
Confirmed removed in d4d151e55bca15bb24627860a9aa592d56bea9f7

2024-04-02 23:20 UTC, metavida commented on pagerduty/event_orchestration_cache_variable_util.go
> +		time.Sleep(2 * time.Second)
Confirmed removed in d4d151e55bca15bb24627860a9aa592d56bea9f7

2024-04-03 15:35 UTC, imjaroiswebdev commented on go.mod
> +replace github.com/heimweh/go-pagerduty => github.com/c-kaieong/go-pagerduty v0.0.0-20240321202501-cb1dc594997d
Just to remind you ✌🏽 @c-kaieong https://github.com/heimweh/go-pagerduty/pull/149 has been merged, so We can move on with dropping this dependency replacement and dep udpate.

2024-04-03 20:02 UTC, imjaroiswebdev approved these changes

2024-04-03 20:02 UTC, merged