Add resource and data source for Alert Grouping Setting
PagerDuty/terraform-provider-pagerduty pull request #935
Opened 2024-10-04 17:26 UTC by cjgajard

```
=== RUN   TestAccDataSourcePagerDutyAlertGroupingSetting_Time
--- PASS: TestAccDataSourcePagerDutyAlertGroupingSetting_Time (17.49s)
=== RUN   TestAccDataSourcePagerDutyAlertGroupingSetting_ContentBased
--- PASS: TestAccDataSourcePagerDutyAlertGroupingSetting_ContentBased (17.08s)
=== RUN   TestAccPagerDutyAlertGroupingSetting_Basic
--- PASS: TestAccPagerDutyAlertGroupingSetting_Basic (30.84s)
=== RUN   TestAccPagerDutyAlertGroupingSetting_ContentBased_WithTimeWindow
--- PASS: TestAccPagerDutyAlertGroupingSetting_ContentBased_WithTimeWindow (16.96s)
=== RUN   TestAccPagerDutyAlertGroupingSetting_Time_WithTimeoutZero
--- PASS: TestAccPagerDutyAlertGroupingSetting_Time_WithTimeoutZero (15.49s)
PASS
ok      github.com/PagerDuty/terraform-provider-pagerduty/pagerdutyplugin       98.391s
```

2024-10-07 18:48 UTC, imjaroiswebdev requested changes

2024-10-07 18:48 UTC, imjaroiswebdev commented on website/docs/r/alert_grouping_setting.html.markdown
> +* `services` - (Required) The list IDs of services associated to this setting.
```suggestion
* `services` - (Required) [Updating causes resource replacement] The list IDs of services associated to this setting.
```

2024-10-11 20:11 UTC, imjaroiswebdev approved these changes
Great job @cjgajard! 🏆 There are a good amount of users waiting for this to be released to tested 💪🏽 Thank you!

2024-10-11 20:11 UTC, merged

2024-12-26 18:02 UTC, sgujavarthy commented on website/docs/d/alert_grouping_setting.html.markdown
> +* `timeout` - The duration in minutes within which to automatically group incoming alerts. This setting is only required and applies when `type` is set to `time`. To continue grouping alerts until th
the documentation regarding the timeout is incorrect. Apparently, the PagerDuty APIs expects the value in seconds, while the documentation says it is in minutes.

Here is the response from _terraform apply_ command:

![image](https://github.com/user-attachments/assets/e4d8106b-ba04-45e5-a3bf-26583f7719d6)